# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_register_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='total',
        ),
    ]
